a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
print("Addition is:", a + b)
print("Subtraction is:", a - b)
print("Multiplication is:", a*b)
print("Modulo is:", a % b)
